export const LIMITS = {
  FORM_TITLE_MAX: 120,
  FORM_DESCRIPTION_MAX: 500,
  FORM_FIELDS_MAX: 100,
  FIELD_LABEL_MAX: 200,
  FIELD_DESCRIPTION_MAX: 500,
  FIELD_PLACEHOLDER_MAX: 100,
  SHORT_TEXT_MAX_CHARS: 200,
  LONG_TEXT_MAX_CHARS: 2500,
  EMAIL_MAX_CHARS: 100,
  URL_MAX_CHARS: 2048,
  DROPDOWN_OPTIONS_MAX: 50,
  SINGLE_CHOICE_OPTIONS_MAX: 20,
  MULTI_CHOICE_OPTIONS_MAX: 20,
  MATRIX_ROWS_MAX: 20,
  MATRIX_COLS_MAX: 10,
  OPTION_LABEL_MAX: 150,
  SECTION_TITLE_MAX: 120,
  STATEMENT_TEXT_MAX: 1000,
  FILE_MAX_SIZE_MB_DEFAULT: 10,
  FILE_MAX_SIZE_MB_ABSOLUTE: 50,
  FILE_EXTENSIONS_ALLOWED: [
    'pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt',
    'png', 'jpg', 'jpeg', 'gif', 'webp', 'mp4', 'mov'
  ]
} as const;
